default: &default
  adapter: postgresql
  encoding: unicode
  database: nikitash
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: tn_qna_development

test:
  <<: *default
  database: tn_qna_test
