development:
  mysql41: 9306
  enable_star: 1
  min_infix_len: 4
test:
  mysql41: 9307
  enable_star: 1
  min_infix_len: 4
production:
  pid_file: /home/deployer/qna/shared/tmp/searchd.pid
  mysql41: 9306
  enable_star: 1
  min_infix_len: 4
